# Generated by Django 4.0.3 on 2023-10-03 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('petname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and contain only numbers.', regex='^\\d{10}$')])),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and contain only numbers.', regex='^\\d{10}$')])),
                ('message_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostelbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('petname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and contain only numbers.', regex='^\\d{10}$')])),
                ('booking_from', models.DateField()),
                ('booking_to', models.DateField()),
            ],
        ),
    ]
