# Generated by Django 4.0.3 on 2023-10-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Appointement',
        ),
    ]
