# Generated by Django 4.0.3 on 2023-10-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_booking_appointement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointement',
            new_name='Booking',
        ),
    ]
